-- MySQL Script generated by MySQL Workbench
-- sáb 15 abr 2023 11:39:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Module` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `subject` ENUM('Matemática', 'Português', 'Redação', 'Geografia', 'História', 'Ciências') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1000) NOT NULL,
  `idModule` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Question_Module1_idx` (`idModule` ASC) ,
  CONSTRAINT `fk_Question_Module1`
    FOREIGN KEY (`idModule`)
    REFERENCES `Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alternative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `isCorrect` TINYINT NOT NULL,
  `idQuestion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Alternative_Question1_idx` (`idQuestion` ASC) ,
  CONSTRAINT `fk_Alternative_Question1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `Question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `StudyWeek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudyWeek` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marker` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lesson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `videoURL` VARCHAR(1000) NOT NULL,
  `idModule` INT NOT NULL,
  `idStudyWeek` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Lession_Module_idx` (`idModule` ASC) ,
  INDEX `fk_Lession_StudyWeek1_idx` (`idStudyWeek` ASC) ,
  CONSTRAINT `fk_Lession_Module`
    FOREIGN KEY (`idModule`)
    REFERENCES `Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lession_StudyWeek1`
    FOREIGN KEY (`idStudyWeek`)
    REFERENCES `StudyWeek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `completeName` VARCHAR(100) NOT NULL,
  `function` ENUM('Professor', 'Administrador', 'Aluno') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `idLession` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Coment_Lession1_idx` (`idLession` ASC) ,
  INDEX `fk_Coment_User1_idx` (`idUser` ASC) ,
  CONSTRAINT `fk_Coment_Lession1`
    FOREIGN KEY (`idLession`)
    REFERENCES `Lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coment_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exam` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Exam_User1_idx` (`idUser` ASC) ,
  CONSTRAINT `fk_Exam_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ExamModule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ExamModule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correctQuestions` INT NOT NULL,
  `isProblem` TINYINT NULL,
  `idExam` INT NOT NULL,
  `totalQuestions` INT NOT NULL,
  `idModule` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CorrectByModule_Exam1_idx` (`idExam` ASC) ,
  INDEX `fk_ExamModules_Module1_idx` (`idModule` ASC) ,
  CONSTRAINT `fk_CorrectByModule_Exam1`
    FOREIGN KEY (`idExam`)
    REFERENCES `Exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExamModules_Module1`
    FOREIGN KEY (`idModule`)
    REFERENCES `Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `StudyPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudyPlan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idExam` INT NOT NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_StudyPlan_Exam1_idx` (`idExam` ASC) ,
  INDEX `fk_StudyPlan_User1_idx` (`idUser` ASC) ,
  CONSTRAINT `fk_StudyPlan_Exam1`
    FOREIGN KEY (`idExam`)
    REFERENCES `Exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudyPlan_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `SuggestedModule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SuggestedModule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idStudyPlan` INT NOT NULL,
  `idModule` INT NOT NULL,
  INDEX `fk_StudyPlan_has_Module_Module1_idx` (`idModule` ASC) ,
  INDEX `fk_StudyPlan_has_Module_StudyPlan1_idx` (`idStudyPlan` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_StudyPlan_has_Module_StudyPlan1`
    FOREIGN KEY (`idStudyPlan`)
    REFERENCES `StudyPlan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudyPlan_has_Module_Module1`
    FOREIGN KEY (`idModule`)
    REFERENCES `Module` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `UserAnswer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserAnswer` (
  `id` INt NOT NULL AUTO_INCREMENT,
  `idExamModule` INT NOT NULL,
  `idQuestion` INT NOT NULL,
  `UserRightAnswer` TINYINT NULL,
  `chosenAnswer` INT NULL,
  INDEX `fk_QuestionByModule_has_Question_Question1_idx` (`idQuestion` ASC) ,
  INDEX `fk_QuestionByModule_has_Question_QuestionByModule1_idx` (`idExamModule` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_QuestionByModule_has_Question_QuestionByModule1`
    FOREIGN KEY (`idExamModule`)
    REFERENCES `ExamModule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuestionByModule_has_Question_Question1`
    FOREIGN KEY (`idQuestion`)
    REFERENCES `Question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(300) NOT NULL,
  `idLession` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Material_Lesson1_idx` (`idLession` ASC) ,
  CONSTRAINT `fk_Material_Lesson1`
    FOREIGN KEY (`idLession`)
    REFERENCES `Lesson` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
