-- MySQL Script generated by MySQL Workbench
-- seg 03 abr 2023 21:09:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Module` (
  `idModule` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `subject` ENUM('Matemática', 'Português', 'Redação', 'Geografia', 'História', 'Ciências') NOT NULL,
  PRIMARY KEY (`idModule`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `Module_idModule` INT NOT NULL,
  PRIMARY KEY (`idQuestion`),
  INDEX `fk_Question_Module1_idx` (`Module_idModule` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Module1`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `Alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Alternative` (
  `idAlternative` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `isCorrect` TINYINT NOT NULL,
  `Question_idQuestion` INT NOT NULL,
  PRIMARY KEY (`idAlternative`),
  INDEX `fk_Alternative_Question1_idx` (`Question_idQuestion` ASC) VISIBLE,
  CONSTRAINT `fk_Alternative_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `StudyWeek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudyWeek` (
  `idStudyWeek` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idStudyWeek`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `Lession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lession` (
  `idLession` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `VideoURL` VARCHAR(200) NOT NULL,
  `Module_idModule` INT NOT NULL,
  `StudyWeek_idStudyWeek` INT NOT NULL,
  PRIMARY KEY (`idLession`),
  INDEX `fk_Lession_Module_idx` (`Module_idModule` ASC) VISIBLE,
  INDEX `fk_Lession_StudyWeek1_idx` (`StudyWeek_idStudyWeek` ASC) VISIBLE,
  CONSTRAINT `fk_Lession_Module`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lession_StudyWeek1`
    FOREIGN KEY (`StudyWeek_idStudyWeek`)
    REFERENCES `StudyWeek` (`idStudyWeek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `completeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Comment` (
  `idComent` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `Lession_idLession` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idComent`),
  INDEX `fk_Coment_Lession1_idx` (`Lession_idLession` ASC) VISIBLE,
  INDEX `fk_Coment_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Coment_Lession1`
    FOREIGN KEY (`Lession_idLession`)
    REFERENCES `Lession` (`idLession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `Exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exam` (
  `idExam` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idExam`),
  INDEX `fk_Exam_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Exam_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `QuestionByModule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuestionByModule` (
  `idQuestionByModule` INT NOT NULL AUTO_INCREMENT,
  `totalQuestions` INT NOT NULL,
  `correctQuestions` INT NOT NULL,
  `isProblem` TINYINT NOT NULL,
  `Exam_idExam` INT NOT NULL,
  PRIMARY KEY (`idQuestionByModule`),
  INDEX `fk_CorrectByModule_Exam1_idx` (`Exam_idExam` ASC) VISIBLE,
  CONSTRAINT `fk_CorrectByModule_Exam1`
    FOREIGN KEY (`Exam_idExam`)
    REFERENCES `Exam` (`idExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `StudyPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudyPlan` (
  `idStudyPlan` INT NOT NULL AUTO_INCREMENT,
  `Exam_idExam` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idStudyPlan`),
  INDEX `fk_StudyPlan_Exam1_idx` (`Exam_idExam` ASC) VISIBLE,
  INDEX `fk_StudyPlan_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_StudyPlan_Exam1`
    FOREIGN KEY (`Exam_idExam`)
    REFERENCES `Exam` (`idExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudyPlan_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `StudyPlan_has_Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StudyPlan_has_Module` (
  `StudyPlan_idStudyPlan` INT NOT NULL,
  `Module_idModule` INT NOT NULL,
  PRIMARY KEY (`StudyPlan_idStudyPlan`, `Module_idModule`),
  INDEX `fk_StudyPlan_has_Module_Module1_idx` (`Module_idModule` ASC) VISIBLE,
  INDEX `fk_StudyPlan_has_Module_StudyPlan1_idx` (`StudyPlan_idStudyPlan` ASC) VISIBLE,
  CONSTRAINT `fk_StudyPlan_has_Module_StudyPlan1`
    FOREIGN KEY (`StudyPlan_idStudyPlan`)
    REFERENCES `StudyPlan` (`idStudyPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudyPlan_has_Module_Module1`
    FOREIGN KEY (`Module_idModule`)
    REFERENCES `Module` (`idModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `QuestionByModule_has_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuestionByModule_has_Question` (
  `QuestionByModule_idQuestionByModule` INT NOT NULL,
  `Question_idQuestion` INT NOT NULL,
  `UserRightAnswer` TINYINT NULL,
  `chosenAnswer` INT NULL,
  PRIMARY KEY (`QuestionByModule_idQuestionByModule`, `Question_idQuestion`),
  INDEX `fk_QuestionByModule_has_Question_Question1_idx` (`Question_idQuestion` ASC) VISIBLE,
  INDEX `fk_QuestionByModule_has_Question_QuestionByModule1_idx` (`QuestionByModule_idQuestionByModule` ASC) VISIBLE,
  CONSTRAINT `fk_QuestionByModule_has_Question_QuestionByModule1`
    FOREIGN KEY (`QuestionByModule_idQuestionByModule`)
    REFERENCES `QuestionByModule` (`idQuestionByModule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuestionByModule_has_Question_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
